name: simplytasks
description: Simple to-do app developed for ToT 2021.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  universal_html: ^1.2.4
  url_launcher: ^5.7.10
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/code_01.png
    - assets/code_02.png
